/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biodataframe;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
/**
 *
 * @author LENOVO
 */
public class BiodataAnnisa extends javax.swing.JFrame {

    /**
     * Creates new form BiodataAnnisa
     */
    public BiodataAnnisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nikText = new javax.swing.JTextField();
        namaText = new javax.swing.JTextField();
        perempuanRadio = new javax.swing.JRadioButton();
        lakiRadio = new javax.swing.JRadioButton();
        pendidikanComboBox = new javax.swing.JComboBox<>();
        DaftarButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatText = new javax.swing.JTextArea();
        NoTelpText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        memasakCheckBox = new javax.swing.JCheckBox();
        OlahragaCheckBox = new javax.swing.JCheckBox();
        TanggalText = new javax.swing.JTextField();
        IPKText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIK");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Pendidikan");

        jLabel6.setText("No.Telp");

        jLabel7.setText("Tanggal Lahir");

        nikText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikTextActionPerformed(evt);
            }
        });

        perempuanRadio.setText("Perempuan");

        lakiRadio.setText("Laki-laki");
        lakiRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRadioActionPerformed(evt);
            }
        });
        lakiRadio.setActionCommand("Laki-laki");

        pendidikanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "D1", "D2", "D3", "D4/S1", "S2", "S3", " " }));
        pendidikanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendidikanComboBoxActionPerformed(evt);
            }
        });

        DaftarButton.setText("Daftar");
        DaftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Hobby");

        alamatText.setColumns(20);
        alamatText.setRows(5);
        jScrollPane2.setViewportView(alamatText);

        NoTelpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoTelpTextActionPerformed(evt);
            }
        });

        jLabel9.setText("IPK");

        memasakCheckBox.setText("Memasak");
        memasakCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memasakCheckBoxActionPerformed(evt);
            }
        });

        OlahragaCheckBox.setText("Olahraga");

        TanggalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalTextActionPerformed(evt);
            }
        });

        IPKText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPKTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DaftarButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lakiRadio)
                        .addGap(18, 18, 18)
                        .addComponent(perempuanRadio))
                    .addComponent(namaText)
                    .addComponent(NoTelpText)
                    .addComponent(jScrollPane2)
                    .addComponent(nikText)
                    .addComponent(pendidikanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(memasakCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OlahragaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TanggalText)
                    .addComponent(IPKText))
                .addGap(0, 63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lakiRadio)
                    .addComponent(jLabel4)
                    .addComponent(perempuanRadio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NoTelpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TanggalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pendidikanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(memasakCheckBox)
                    .addComponent(OlahragaCheckBox))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(IPKText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(DaftarButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        perempuanRadio.setActionCommand("Perempuan");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nikTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikTextActionPerformed

    private void pendidikanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendidikanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pendidikanComboBoxActionPerformed

    private void lakiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiRadioActionPerformed

    private void DaftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarButtonActionPerformed

StringBuilder sb = new StringBuilder();
sb.append("NIK: ").append(nikText.getText()).append("\n");
sb.append("Nama: ").append(namaText.getText()).append("\n");
sb.append("Alamat: ").append(alamatText.getText()).append("\n");

// Memilih jenis kelamin
String gender = "-";
if (lakiRadio.isSelected()) {
    gender = lakiRadio.getText();
} else if (perempuanRadio.isSelected()) {
    gender = perempuanRadio.getText();
}
sb.append("Jenis Kelamin: ").append(gender).append("\n");

// Validasi No.Telp hanya untuk angka
String noTelp = NoTelpText.getText();

if (noTelp.matches("\\d*") && !noTelp.isEmpty()) {

    sb.append("No.Telp: ").append(noTelp).append("\n");
} else {

    JOptionPane.showMessageDialog(this, "Nomor Telepon tidak valid. Harap masukkan hanya angka.", "Error", JOptionPane.ERROR_MESSAGE);

}

// Tanggal Lahir 
String tanggalLahirStr = TanggalText.getText();

DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");

try {
    LocalDate tanggalLahir = LocalDate.parse(tanggalLahirStr, formatter);
    long usia = ChronoUnit.YEARS.between(tanggalLahir, LocalDate.now());

    if (usia < 18) {
        JOptionPane.showMessageDialog(this, "Anda belum cukup umur untuk melamar pekerjaan ini", "Info", JOptionPane.INFORMATION_MESSAGE);
        return; 
    } else {
        sb.append("Tanggal Lahir: ").append(tanggalLahirStr).append("\n");
        sb.append("Usia: ").append(usia).append(" tahun\n");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Format tanggal lahir tidak valid. Gunakan format dd-MM-yyyy", "Error", JOptionPane.ERROR_MESSAGE);
    return; 
}

sb.append("NIK: ").append(nikText.getText()).append("\n");

JOptionPane.showMessageDialog(this, sb.toString(), "Biodata", JOptionPane.INFORMATION_MESSAGE);


// Memilih Pendidikan
Object pendidikanItem = pendidikanComboBox.getSelectedItem();
if (pendidikanItem != null) {
    sb.append("Pendidikan: ").append(pendidikanItem.toString()).append("\n");
} else {
    sb.append("Pendidikan: -\n");
}

// Hobby
sb.append("Hobi: ");
if (memasakCheckBox.isSelected()) {
    sb.append(memasakCheckBox.getText()).append("\n");
}
if (OlahragaCheckBox.isSelected()) {
    sb.append(OlahragaCheckBox.getText()).append("\n");
}

// IPK
String ipkText = IPKText.getText();
try {
    double ipk = Double.parseDouble(ipkText);

    if (ipk >= 0.00 && ipk <= 4.00) {
        sb.append("IPK: ").append(ipkText).append("\n");
    } else {
        sb.append("IPK tidak valid\n");
    }
} catch (NumberFormatException e) {
    sb.append("IPK tidak valid\n");
}

JOptionPane.showMessageDialog(this, sb.toString(), "Biodata", JOptionPane.INFORMATION_MESSAGE);

Object[] options = {"Anda Berhasil Mendaftar"};
int result = JOptionPane.showOptionDialog(
        this, 
        "Apakah Anda ingin keluar?", 
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE,
        null, 
        options, 
        options[1]); 
if (result == JOptionPane.YES_OPTION) {
    System.exit(0); 
}




// TODO add your handling code here:
    }//GEN-LAST:event_DaftarButtonActionPerformed

    private void NoTelpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoTelpTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoTelpTextActionPerformed

    private void memasakCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memasakCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memasakCheckBoxActionPerformed

    private void TanggalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalTextActionPerformed

    private void IPKTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPKTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPKTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataAnnisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataAnnisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataAnnisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataAnnisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataAnnisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DaftarButton;
    private javax.swing.JTextField IPKText;
    private javax.swing.JTextField NoTelpText;
    private javax.swing.JCheckBox OlahragaCheckBox;
    private javax.swing.JTextField TanggalText;
    private javax.swing.JTextArea alamatText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton lakiRadio;
    private javax.swing.JCheckBox memasakCheckBox;
    private javax.swing.JTextField namaText;
    private javax.swing.JTextField nikText;
    private javax.swing.JComboBox<String> pendidikanComboBox;
    private javax.swing.JRadioButton perempuanRadio;
    // End of variables declaration//GEN-END:variables
}
